services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050" # Map backend container's port 5000 to host's port 5050
    environment:
      - NODE_ENV=production
      - PORT=5050
      - DATA_FOLDER=/app/data
    volumes:
      - ./data:/app/data  # Map the internal data folder to /app/data in the container
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4040:3000" # Map frontend container's port 3000 to host's port 4040
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5050  # Use Docker service name for backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
