#!/usr/bin/env python3
"""Write WHERE_TO_EDIT_TEXT.md -- every editable sentence and its file:line.

    cd heap/frontend && python3 tools/map_copy.py

Regenerate after moving code around. The map is generated rather than written
by hand so it cannot drift from the source.

It reads the JSX, not the rendered page, so it finds text in states you would
have to trigger in a browser to see -- error messages, empty states, tooltips.
"""
import os
import re
from collections import OrderedDict

SRC = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "WHERE_TO_EDIT_TEXT.md")

# Which components serve which route. Page files are thin; the prose is in the
# components they mount, which is the whole reason this map exists.
PAGES = OrderedDict([
    ("/", ["pages/Home.js"]),
    ("/downloads", ["pages/Downloads.js"]),
    ("/results/main", ["pages/subpages/MainResults.js", "components/redesign/"]),
    ("/results/summary", ["pages/subpages/HeapSummary.js", "components/redesign/"]),
    ("/results/associations", ["pages/subpages/Associations.js"]),
    ("/results/architecture", ["pages/subpages/Interactions.js"]),
    ("/results/mediation", ["pages/subpages/Mediation.js"]),
    ("/results/intervention", ["pages/subpages/Intervention.js", "components/intervention/"]),
    ("/results/enrichment", ["pages/subpages/EnrichmentGuide.js", "components/enrichment/"]),
    ("/results/causal", ["pages/subpages/CausalGuide.js", "components/TriadDAG.js",
                         "components/TriadBuilder.js", "components/MotifGlyph.js",
                         "components/ColocRegional.js", "components/PDEffects.js"]),
    ("/results/pes", ["pages/subpages/PesGuide.js", "components/pes/"]),
    ("/results/gwas", ["pages/subpages/Gwas.js"]),
    ("/documentation/about", ["pages/subpages/AboutHeap.js"]),
    ("/documentation/quickstart", ["pages/subpages/QuickStart.js"]),
    ("/documentation/methods", ["pages/subpages/DetailedMethods.js"]),
    ("/documentation/cite", ["pages/subpages/Cite.js"]),
    ("/documentation/api", ["pages/subpages/ApiDocs.js"]),
])

# A prose block is a JSX text run, or a title/subtitle prop. Short runs are
# labels and axis titles -- listed separately so the long stuff stays readable.
RUNS = [
    # props
    ("title", re.compile(r"title=\{?[\"'`]([^\"'`]{12,})[\"'`]")),
    ("subtitle", re.compile(r"subtitle=\{?\(?\s*[\"'`]([^\"'`]{12,})[\"'`]")),
    # object fields and consts -- the landing page's hero and every card body
    # live here, and a props-and-JSX-only scan misses all of them.
    ("field", re.compile(r"^\s*(?:body|lead|blurb|payoff|question|note|label|title|subtitle|text)"
                         r":\s*\n?\s*[\"'`]([^\"'`]{12,})[\"'`]", re.M)),
    ("const", re.compile(r"^const [A-Z_]+ =\s*\n?\s*[\"'`]([^\"'`]{12,})[\"'`]", re.M)),
    # plain JSX text runs
    ("text", re.compile(r">\s*\n?\s*([A-Z][^<>{}\n][^<>{}]{25,})", re.M)),
]
LONG = 20          # words: a sentence worth rewriting, versus a label


def expand(entries):
    out = []
    for e in entries:
        p = os.path.join(SRC, e)
        if e.endswith("/"):
            out += sorted(os.path.join(p, f) for f in os.listdir(p) if f.endswith(".js"))
        elif os.path.exists(p):
            out.append(p)
    return out


# `'first half ' + 'second half'` is ONE sentence to a reader and two literals
# to a regex. Counting only the first fragment made a 43-word hero look like 10
# and drop below the threshold, so follow the `+` chain and join it.
JOIN = re.compile(r"\s*\+\s*[\"'`]([^\"'`]*)[\"'`]")


def full_literal(s, end, first):
    """Text of a literal starting at `first`, following any + concatenation."""
    parts, pos = [first], end
    while True:
        m = JOIN.match(s, pos)
        if not m:
            return " ".join(" ".join(parts).split()), pos
        parts.append(m.group(1))
        pos = m.end()


def blocks(path):
    s = open(path).read()
    found = {}
    for kind, rx in RUNS:
        for m in rx.finditer(s):
            txt, _ = full_literal(s, m.end(), m.group(1))
            if txt.startswith(("//", "/*", "*")) or "=>" in txt or "${" in txt[:4]:
                continue
            line = s[: m.start()].count("\n") + 1
            # a longer match at the same line wins -- props and fields overlap
            if line not in found or len(txt.split()) > found[line][1]:
                found[line] = (kind, len(txt.split()), txt)
    return sorted(found.items())


def main():
    L = ["# Where to edit the website's text", "",
         "Generated by `tools/map_copy.py` -- rerun it after moving code.", "",
         "**How to use this.** Find the sentence you want to change, open that",
         "file at that line, edit the words. Nothing here needs a build step: the",
         "dev server reloads on save.", "",
         "**Two things to know.**", "",
         "1. Text is often split across lines and joined, like",
         "   `'first half ' + 'second half'`. Edit the whole expression and keep",
         "   the quotes matched.",
         "2. `${...}` inserts a computed value -- a count, a name, a number. Keep",
         "   those and change the words around them.", "",
         "**Not listed:** axis titles, legend labels and column headers under",
         f"{LONG} words live next to the plot they belong to. Grep the exact words",
         "to find one: `grep -rn \"the words you see\" --include=*.js src/`", "",
         "---", ""]

    for route, entries in PAGES.items():
        files = expand(entries)
        rows = [(f, b) for f in files for b in blocks(f)]
        longs = [(f, ln, k, n, t) for f, (ln, (k, n, t)) in rows if n >= LONG]
        shorts = sum(1 for f, (ln, (k, n, t)) in rows if n < LONG)
        if not rows:
            continue
        L.append(f"## `{route}`")
        L.append("")
        L.append(f"{len(longs)} passages of {LONG}+ words; {shorts} shorter labels not listed.")
        L.append("")
        cur = None
        for f, ln, k, n, t in sorted(longs, key=lambda r: (r[0], r[1])):
            rel = os.path.relpath(f, SRC)
            if rel != cur:
                cur = rel
                L.append(f"**`src/{rel}`**")
                L.append("")
            L.append(f"- **{rel.split('/')[-1]}:{ln}** ({n} words, {k})")
            L.append(f"  > {t[:150]}{'...' if len(t) > 150 else ''}")
        L.append("")

    open(OUT, "w").write("\n".join(L) + "\n")
    print(f"  wrote {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
