name: Deploy Frontend to Firebase Hosting

on:
  workflow_run:
    workflows: ["Deploy Backend to Google Cloud Run"]
    types:
      - completed
  push:
    paths:
      - 'heap/frontend/**'
      - '.github/workflows/deploy-firebase.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Authenticate with Google Cloud (for Google Cloud services)
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Step 3: Set up Firebase CLI
    - name: Set up Firebase CLI
      run: |
        curl -sL https://firebase.tools | bash  # Install Firebase CLI
        firebase --version  # Check Firebase CLI version

    # Step 4: Install Node.js and dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # Update to Node.js 22

    # Step 5: Install dependencies
    - name: Install dependencies
      run: |
        cd heap/frontend  # Navigate to the frontend directory
        npm install  # Install the app dependencies
    
    # Step 5.1:
    - name: Create .env file with backend URL
      run: |
        cd heap/frontend  # Navigate to the frontend directory
        echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" > .env
        echo "Other custom variables can go here if needed"
  
    # Step 6: Build React app
    - name: Build React app
      run: |
        cd heap/frontend  # Navigate to the frontend directory
        npm run build  # This creates the static files in 'build' folder

    # Step 7: Firebase Deployment
    - name: Deploy to Firebase Hosting
      run: |
        cd heap/frontend  # Navigate to the frontend directory
        firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_AUTH_TOKEN }}